version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs"
  ]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["7"]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["8"]

[[analyzers]]
name = "shell"
enabled = true